values: (( &temporary ))
helpers: (( &temporary ))

apiVersion: v1
kind: Secret
metadata:
  name: (( values.name "-credentials" ))
  namespace: (( values.namespace ))
data: (( helpers.secretdata(values.secrets) ))
