apiVersion: v1
kind: Pod
metadata:
  name: memory-demo
  namespace: mem-example
  label:
    app: demo
spec:
  containers:
  - name: memory-demo-ctr
    image: polinux/stress:v1.0
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "400Mi"
        cpu: "200m"
    args:
    - --vm
    - "1"
    - --vm-bytes
    - "150M"
    - --vm-hang
    - "1"
    - --debug
    command:
    - "stress"
